import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

// Generated by Selenium IDE
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;

public class MyStepdefs {
    private WebDriver driver;

    public MyStepdefs() {
        driver = new ChromeDriver();
        driver.get("https://membership.basketballengland.co.uk/NewSupporterAccount");
        driver.manage().window().setSize(new Dimension(1920, 1048));
    }

    @Given("I have entered date of birth {string}")
    public void iHaveEnteredDateOfBirth(String birthdate) {
        driver.findElement(By.id("dp")).sendKeys(birthdate);
    }

    @And("I have entered first name {string}")
    public void iHaveEnteredFirstName(String firstname) {
        driver.findElement(By.id("member_firstname")).sendKeys(firstname);
    }

    @And("I have entered last name {string}")
    public void iHaveEnteredLastName(String lastname) {
        driver.findElement(By.id("member_lastname")).sendKeys(lastname);
    }

    @And("I have entered email and confirmed email {string}")
    public void iHaveEnteredEmailAndConfirmedEmail(String email) {
        driver.findElement(By.id("member_emailaddress")).sendKeys(email);
        driver.findElement(By.id("member_confirmemailaddress")).sendKeys(email);
    }

    @And("I have entered password and confirmed password {string} {string}")
    public void iHaveEnteredPasswordAndConfirmedPassword(String pass, String confirmPass) {
        driver.findElement(By.id("signupunlicenced_password")).sendKeys(pass);
        driver.findElement(By.id("signupunlicenced_confirmpassword")).sendKeys(confirmPass);
    }

    @And("I have checked Terms and Conditions")
    public void iHaveCheckedTermsAndConditions() {
        driver.findElement(By.xpath("//*[@id=\"signup_form\"]/div[11]/div/div[2]/div[1]/label/span[3]")).click();
    }

    @And("I have checked Over 18 and Code of Conduct")
    public void iHaveCheckedOverAndCodeOfConduct() {
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(2) > label")).click();
        driver.findElement(By.cssSelector(".md-checkbox:nth-child(7) > label")).click();
    }

    @When("I press the join button")
    public void iPressTheJoinButton() {
        driver.findElement(By.name("join")).click();
    }

    @Then("I am registered")
    public void iAmRegistered() {
        String actual = driver.findElement(By.cssSelector(".bold:nth-child(1)")).getText();
        String expected = "THANK YOU FOR CREATING AN ACCOUNT WITH BASKETBALL ENGLAND";
        System.out.println("iAmRegistered:" + actual + " " + expected + "\n");
        assertEquals(actual, expected);
    }

    @Then("I failed to get registered because of missing last name")
    public void iFailedToGetRegisteredBecauseOfMissingLastName() {
        String actual = driver.findElement(By.cssSelector(".warning > span")).getText();
        String expected = "Last Name is required";

        System.out.println("iFailedToGetRegisteredBecauseOfMissingLastName:" + actual + " == " + expected + "\n");
        assertEquals(actual, expected);
    }

    @Then("I failed to get registered because of mismatch password")
    public void iFailedToGetRegisteredBecauseOfMismatchPassword() {
        String actual = driver.findElement(By.cssSelector(".warning > span")).getText();
        String expected = "Password did not match";

        System.out.println("iFailedToGetRegisteredBecauseOfMismatchPassword:" + actual + " == " + expected + "\n");
        assertEquals(actual, expected);
    }

    @Then("I failed to get registered because of not agreeing with the terms and conditions")
    public void iFailedToGetRegisteredBecauseOfNotAgreeingWithTheTermsAndConditions() {
        String actual = driver.findElement(By.cssSelector(".warning > span")).getText();
        String expected = "You must confirm that you have read and accepted our Terms and Conditions";

        System.out.println("iFailedToGetRegisteredBecauseOfNotAgreeingWithTheTermsAndConditions:" + actual + " == " + expected + "\n");
        assertEquals(actual, expected);
    }
}
